
#=====================================================
# PHYSICAL PROCESSES
#=====================================================

# TASK
# BASED ON THE SPECT PHYSICS LIST
# DEFINE A LIST OF PROCESSES FOR PET APPLICATIONS

/gate/physics/addProcess PhotoElectric
/gate/physics/processes/PhotoElectric/setModel StandardModel

/gate/physics/addProcess Compton
/gate/physics/processes/Compton/setModel StandardModel

/gate/physics/addProcess RayleighScattering
/gate/physics/processes/RayleighScattering/setModel PenelopeModel

/gate/physics/addProcess ElectronIonisation
/gate/physics/processes/ElectronIonisation/setModel StandardModel e-
/gate/physics/processes/ElectronIonisation/setModel StandardModel e+

/gate/physics/addProcess Bremsstrahlung
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e+


/gate/physics/addProcess RadioactiveDecay

/gate/physics/addProcess PositronAnnihilation

/gate/physics/addProcess eMultipleScattering e+
/gate/physics/addProcess eMultipleScattering e-

/gate/physics/processList Enabled
/gate/physics/processList Initialized

#=====================================================
# CUTS
#=====================================================

# TASK
# DEFINE A CUT VALUE TO LIMIT THE PRODUCTION OF 
# SECONDARY PHOTON AND ELECTRON IN THE DETECTOR
#
/gate/physics/Gamma/SetCutInRegion      crystal 1.0 cm
/gate/physics/Electron/SetCutInRegion   crystal 1.0 cm

#
# DEFINE CUT FOR REGULAR PHANTOM
#
#/gate/physics/Gamma/SetCutInRegion      phantom 0.1 mm
#/gate/physics/Electron/SetCutInRegion   phantom 0.1 mm
#/gate/physics/Positron/SetCutInRegion   phantom 0.1 mm
#
# ...AND FOR VOXEL PHANTOM
#
/gate/physics/Gamma/SetCutInRegion      voxel_Phantom 0.1 mm
/gate/physics/Electron/SetCutInRegion   voxel_Phantom 0.1 mm
/gate/physics/Positron/SetCutInRegion   voxel_Phantom 0.1 mm


#/gate/physics/SetMaxStepSizeInRegion    phantom 0.01 mm



